# Generated by Django 4.0.4 on 2022-07-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
    ]
